In [2]:
from dask.distributed import Client 

client = Client()

client

c:\Users\karth\anaconda3\envs\test\lib\site-packages\distributed\node.py:180: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 49332 instead
  warnings.warn(


<Client: 'tcp://127.0.0.1:49333' processes=4 threads=8, memory=15.86 GiB>

In [3]:
client.dashboard_link

'http://127.0.0.1:49332/status'

In [4]:
import numpy as np 
import os
import pickle
import shutil
from scipy import sparse
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from immuneML.IO.ml_method.MLMethodConfiguration import MLMethodConfiguration
from immuneML.data_model.encoded_data.EncodedData import EncodedData
from immuneML.environment.EnvironmentSettings import EnvironmentSettings
from immuneML.environment.Label import Label
from immuneML.ml_methods.KNN import KNN
from immuneML.ml_methods.SVM import SVM
from immuneML.util.PathBuilder import PathBuilder
from immuneML.ml_methods.LogisticRegression import LogisticRegression


c:\Users\karth\anaconda3\envs\test\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
from pathlib import Path

import dill
import numpy as np
import pkg_resources
import yaml
from sklearn.metrics import SCORERS
from sklearn.model_selection import RandomizedSearchCV
from sklearn.utils.validation import check_is_fitted

from immuneML.data_model.encoded_data.EncodedData import EncodedData
from immuneML.environment.Label import Label
from immuneML.ml_methods.MLMethod import MLMethod
from immuneML.ml_methods.util.Util import Util
from immuneML.ml_metrics.Metric import Metric
from immuneML.util.FilenameHandler import FilenameHandler
from immuneML.util.PathBuilder import PathBuilder

In [5]:
x = np.array([[1, 0, 0], [0, 1, 1], [1, 1, 1], [0, 1, 1]])
y = {"default": np.array([1, 0, 2, 0])}

In [29]:
import numpy as np
import pandas as pd

import dask.dataframe as dd
import dask.array as da
import dask.bag as db


(4,)

In [93]:
X = da.random.randint(0, 1 , (2000, 2000))



In [94]:
X

dask.array<randint, shape=(20000, 20000), dtype=int32, chunksize=(5000, 5000), chunktype=numpy.ndarray>

AttributeError: 'Array' object has no attribute 'head'

In [135]:
y = da.random.randint(0,1,  2000)

In [136]:
y.compute_chunk_sizes()

dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

In [137]:
lr = LogisticRegression()

In [138]:
Y = {"test" : y }

In [139]:
Y

{'test': dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>}

In [140]:
X

dask.array<randint, shape=(20000, 20000), dtype=int32, chunksize=(5000, 5000), chunktype=numpy.ndarray>

In [141]:
Y

{'test': dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>}

In [142]:
lr = LogisticRegression()

In [143]:
X.compute_chunk_sizes()
Y["test"].compute_chunk_sizes()

dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

In [144]:
encoded_data = EncodedData(X,Y)

In [107]:
encoded_data.examples

dask.array<randint, shape=(20000, 20000), dtype=int32, chunksize=(5000, 5000), chunktype=numpy.ndarray>

In [145]:
encoded_data.labels

{'test': dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>}

In [146]:
label = Label("test")

In [128]:
y.compute_chunk_sizes()

dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

In [110]:
client.nthreads

<bound method Client.nthreads of <Client: 'tcp://127.0.0.1:60687' processes=4 threads=8, memory=15.86 GiB>>

In [147]:
class_mapping = Util.make_class_mapping(encoded_data.labels[label.name])

ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

In [60]:
def fit( encoded_data , label):

    class_mapping = Util.make_class_mapping()



SyntaxError: invalid syntax (2587897442.py, line 1)

In [152]:
cy = encoded_data.labels[label.name].compute_chunk_sizes()


In [153]:
cy.shape

(20000,)

In [159]:
classes = np.unique(cy)

In [161]:
classes = classes.compute()

In [162]:
classes

array([0, 1])

In [158]:
classes.shape[0] ==

2

In [164]:
import xarray as xr

In [150]:
for classes

dask.array<getitem, shape=(nan,), dtype=int32, chunksize=(nan,), chunktype=numpy.ndarray>

In [111]:
classes = np.unique(encoded_data.labels[label.name])


In [112]:
classes

dask.array<getitem, shape=(nan,), dtype=int32, chunksize=(nan,), chunktype=numpy.ndarray>

In [70]:
label.name

'test'

In [71]:
encoded_data.labels

{'test': dask.array<random_sample, shape=(20000,), dtype=float64, chunksize=(20000,), chunktype=numpy.ndarray>}

In [73]:
classes = da.unique(encoded_data.labels[label.name])


In [126]:
Y["test"][:5]

array([0, 0, 1, 1, 1])

In [75]:
for cls in classes:
    cls

ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

In [74]:
classes.shape[0]

nan

In [63]:
Util.make_class_mapping(encoded_data.labels[label.name])

ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`

In [165]:
classes = encoded_data.labels[label.name]


In [166]:
classes = classes.compute()

In [179]:
classes = np.unique(classes)

array([0, 1])

In [183]:
classes = encoded_data.labels[label.name]
classes = classes.compute()
classes = np.unique(classes)
if classes.shape[0] == 2:
    print(classes.shape[0] == 2)

    unique_values = sorted(set(classes))

    assert len(unique_values) == 2, f"MLMethod: there has two be exactly two classes to use this classifier," \
        f" instead got {str(unique_values)[1:-1]}. For multi-class classification, " \
        f"consider some of the other classifiers."

    class_mapping = {0: unique_values[0], 1: unique_values[1]}

else:

    class_mapping = {cls: cls for cls in classes}


True


In [184]:
class_mapping


{0: 0, 1: 1}

In [185]:
feature_names = encoded_data.feature_names

In [186]:
feature_names

In [189]:
encoded_data.labels[label.name]

dask.array<randint, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

In [ ]:
mapped_y = encoded_data.labels[label.name] , class_mapping

In [192]:
type(encoded_data.labels[label.name].persist())

dask.array.core.Array

In [195]:
mapped_y = encoded_data.labels[label.name].compute().astype(object)

In [197]:
switched_mapping = {value: key for key, value in class_mapping.items()}
new_class_type = np.array(list(switched_mapping.values())).dtype


In [198]:
switched_mapping

{0: 0, 1: 1}

dask.array<rechunk-merge, shape=(20000, 20000), dtype=int32, chunksize=(5000, 20000), chunktype=numpy.ndarray>

In [199]:
new_class_type

dtype('int32')

In [202]:
y = encoded_data.labels[label.name].compute()


In [204]:
try:
    y = encoded_data.labels[label.name].compute()
    mapped_y = y.astype(object)
    switched_mapping = {value: key for key, value in class_mapping.items()}
    new_class_type = np.array(list(switched_mapping.values())).dtype


    for i in range(mapped_y.shape[0]):

        mapped_y[i] = switched_mapping[y[i]]

    mapped_y = mapped_y.astype(new_class_type)
except Exception as e:
    logging.exception(f"MLMethod util: error occurred when fitting the model due to mismatch of class types.\n"
                              f"Classes: {y}\nMapping:{class_mapping}")
    raise e


In [206]:
mapped_y.dtype

dtype('int32')

In [207]:
encoded_data.examples

dask.array<randint, shape=(20000, 20000), dtype=int32, chunksize=(5000, 5000), chunktype=numpy.ndarray>

In [208]:
mapped_y

array([1, 1, 0, ..., 1, 1, 0])

In [218]:
Y["test"] = Y["test"].compute()

In [222]:
mapped_y

array([1, 1, 0, ..., 1, 1, 0])

In [219]:
X = encoded_data.examples.compute()
Y = Y


In [ ]:
lr.fit()

In [220]:
Y

{'test': array([1, 1, 0, ..., 1, 1, 0])}

In [209]:
import joblib

In [250]:
from dask_ml.linear_model import LogisticRegression


In [226]:
mapped_y

array([1, 1, 0, ..., 1, 1, 0])

In [248]:
X

dask.array<rechunk-merge, shape=(20000, 20000), dtype=int32, chunksize=(5000, 20000), chunktype=numpy.ndarray>

In [253]:
mapped_y

dask.array<array, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

tornado.application - ERROR - Uncaught exception GET /groups/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/groups/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "c:\Users\karth\anaconda3\envs\test\lib\site-packages\tornado\websocket.py", line 954, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "c:\Users\karth\anaconda3\envs\test\lib\site-packages\tornado\web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "c:\Users\karth\anaconda3\envs\test\lib\site-packages\bokeh\server\views\ws.py", line 149, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.


In [252]:
LogisticRegression().fit(X,mapped_y)

ValueError: Multiple constant columns detected!

In [246]:
X = da.from_array(X)
mapped_y = da.from_array(mapped_y)


ValueError: Array is already a dask array. Use 'asarray' or 'rechunk' instead.

In [244]:
X = X.rechunk({1: X.shape[1]})


KeyboardInterrupt: 

In [242]:
X

dask.array<rechunk-merge, shape=(20000, 20000), dtype=int32, chunksize=(5000, 20000), chunktype=numpy.ndarray>

In [235]:
mapped_y

dask.array<array, shape=(20000,), dtype=int32, chunksize=(20000,), chunktype=numpy.ndarray>

In [255]:
from sklearn.linear_model import LogisticRegression


In [257]:
client

<Client: 'tcp://127.0.0.1:60687' processes=4 threads=8, memory=15.86 GiB>

In [256]:
with joblib.parallel_backend("dask"):
    LogisticRegression(random_state=0).fit(X,mapped_y)

distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting


TypeError: 'CancelledError' object is not iterable

distributed.nanny - WARNING - Restarting worker


In [221]:
with joblib.parallel_backend("dask", Scatter=[X,Y]):

    lr.fit(EncodedData(X,Y), Label("test"))

distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker


TypeError: 'CancelledError' object is not iterable

Future exception was never retrieved
future: <Future finished exception=PermissionError(13, 'Access is denied', None, 5, None)>
Traceback (most recent call last):
  File "c:\Users\karth\anaconda3\envs\test\lib\site-packages\distributed\process.py", line 32, in _call_and_set_future
    res = func(*args, **kwargs)
  File "c:\Users\karth\anaconda3\envs\test\lib\multiprocessing\process.py", line 133, in terminate
    self._popen.terminate()
  File "c:\Users\karth\anaconda3\envs\test\lib\multiprocessing\popen_spawn_win32.py", line 123, in terminate
    _winapi.TerminateProcess(int(self._handle), TERMINATE)
PermissionError: [WinError 5] Access is denied


In [284]:
import dask.array as da
import dask.delayed
from sklearn.datasets import make_blobs
import numpy as np


In [261]:
x = np.array([[1, 0, 0], [0, 1, 1], [1, 1, 1], [0, 1, 1]])
y = np.array([1, 0, 2, 0])




In [262]:
X = da.from_array(x)


In [281]:
X

dask.array<array, shape=(4, 3), dtype=int32, chunksize=(4, 3), chunktype=numpy.ndarray>

In [263]:
Y = da.from_array(y)

In [282]:
Y

dask.array<array, shape=(4,), dtype=int32, chunksize=(4,), chunktype=numpy.ndarray>

In [302]:
X = da.random.randint(0, 2, (2000, 2000))


In [303]:
Y = da.random.randint(0,2,  2000)

In [304]:
X.compute()[:10]

array([[0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 0]])

In [305]:
Y.compute()[:10]

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1])

In [306]:
from sklearn.linear_model import LogisticRegression


In [307]:
lr = LogisticRegression()

In [308]:
with joblib.parallel_backend("dask"):
    lr.fit(X,Y)


In [309]:
lr.predict(X)


array([0, 0, 1, ..., 1, 0, 1])

In [267]:
LogisticRegression.best_params_, LogisticRegression.best_score_


AttributeError: type object 'LogisticRegression' has no attribute 'best_params_'